# Generated by Django 2.2.7 on 2019-11-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=20)),
                ('apassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('marks_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_no', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('answer_choice_one', models.CharField(max_length=50)),
                ('answer_choice_two', models.CharField(max_length=50)),
                ('answer_choice_three', models.CharField(max_length=50)),
                ('answer_choice_four', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('register_no', models.IntegerField(primary_key=True, serialize=False)),
                ('student_email', models.CharField(max_length=40)),
                ('student_name', models.CharField(max_length=20)),
                ('student_marks', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
